/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierNetworkEnterprise;
import Business.Network.Network;
import Business.Organization.EquipmentSupplierOrganization;
import Business.Organization.FertlizerSupplierOrganization;
import Business.Organization.Organization;
import Business.Organization.SeedSupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EquipmentWorkRequest;
import Business.WorkQueue.FertilizerWorkRequest;
import Business.WorkQueue.SeedWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sakshee
 */
public class OrderSuppliesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public OrderSuppliesJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        valueLabel.setText(enterprise.getName());
        nameTxtField.setText(userAccount.getUsername());
        populateSupplierComboBox(); 
    }
    
    private void populateSupplierComboBox(){
        supplierComboBox1.removeAllItems();
         for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof SupplierNetworkEnterprise) {
                    supplierComboBox1.addItem(enterprise.getName());
                }
             }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantityJTextField = new javax.swing.JTextField();
        categoryJCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        supplierComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(245, 170, 122));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Order Supplies");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        jLabel1.setText("Select Supply");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 130, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 200, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 120, 30));

        jLabel2.setText("Item Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
        add(NameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 130, -1));

        jLabel4.setText("Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 130, -1));

        jLabel6.setText("Quantity");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));
        add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 130, -1));

        categoryJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seed", "Fertilizer", "Equipment" }));
        categoryJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryJComboActionPerformed(evt);
            }
        });
        add(categoryJCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 130, -1));

        jLabel3.setText("Additional Comments");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        supplierComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(supplierComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 130, -1));

        jLabel5.setText("Supplier");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        nameTxtField.setEditable(false);
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        String category=(String) categoryJCombo.getSelectedItem();
        String message = messageJTextField.getText();
        String name = NameJTextField.getText();
        String address = addressJTextField.getText();
        String supplier = (String)supplierComboBox1.getSelectedItem();
        int quantity;
        
        try{
               quantity = Integer.parseInt(quantityJTextField.getText());
            }
            catch(NumberFormatException e)           
                { JOptionPane.showMessageDialog(null,"Please enter number for quantity");
                return;
            }
        
        if(category.equals("")||address.equals("")||supplier.equals("")||name.equals(""))
        {
             JOptionPane.showMessageDialog(null, "Item Name, category, Address and supplier are mandatory");
            return;
        }
        if(category.equals("Seed")){
            SeedWorkRequest request = new SeedWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setSeedName(name);
            request.setAddress(address);
            request.setQuantity(quantity);
            request.setName(userAccount.getUsername());
        
        Organization org = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getName().equalsIgnoreCase(supplier)){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                if (organization instanceof SeedSupplierOrganization) {
                            org = organization;
                            //                            System.out.println("orgname" + organization.getName());
                            org.getWorkQueue().getWorkRequestList().add(request);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                            break;
                       
                }

            }}
        }
        }
        else if(category.equals("Fertilizer")){
            FertilizerWorkRequest request = new FertilizerWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setFertilizerName(name);
            request.setAddress(address);
            request.setQuantity(quantity);
            request.setName(userAccount.getUsername());
        
        
        Organization org = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getName().equalsIgnoreCase(supplier)){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                if (organization instanceof FertlizerSupplierOrganization) {
                            org = organization;
                            //                            System.out.println("orgname" + organization.getName());
                            org.getWorkQueue().getWorkRequestList().add(request);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                            break;
                       
                }

            }}
        }
        }
        else{
            
            EquipmentWorkRequest request = new EquipmentWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setEquipmentName(name);
            request.setAddress(address);
            request.setQuantity(quantity);
            request.setName(userAccount.getUsername());
        
        
        Organization org = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getName().equalsIgnoreCase(supplier)){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                if (organization instanceof EquipmentSupplierOrganization) {
                            org = organization;
                            //                            System.out.println("orgname" + organization.getName());
                            org.getWorkQueue().getWorkRequestList().add(request);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                            break;
                       
                }

            }}
        }
        }
        JOptionPane.showMessageDialog(null,"Order Successfully placed","INFO",JOptionPane.INFORMATION_MESSAGE);
        backJButtonActionPerformed(evt);
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FarmerWorkAreaJPanel dwjp = (FarmerWorkAreaJPanel) component;
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void categoryJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryJComboActionPerformed

    }//GEN-LAST:event_categoryJComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameJTextField;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> categoryJCombo;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JComboBox<String> supplierComboBox1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
