/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.localrestaurants;

import userinterface.FarmerRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.Organization.LocalRestaurantsOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankLoanWorkRequest;
import Business.WorkQueue.EquipmentWorkRequest;
import Business.WorkQueue.FertilizerWorkRequest;
import Business.WorkQueue.MicroLoanWorkRequest;
import Business.WorkQueue.SeedWorkRequest;
import Business.WorkQueue.SubsidyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakshee
 */
public class LRestaurantsWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private LocalRestaurantsOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public LRestaurantsWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, LocalRestaurantsOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system =system;
        valueLabel.setText(enterprise.getName());
        createTabs();
    }
    
     public void createTabs() {
        LRViewLoanRequestsJPanel loanStatus=new LRViewLoanRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Loan Status",loanStatus);
        LRViewMicroLoanRequestsJPanel microLoanStatus=new LRViewMicroLoanRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Micro Loan Status",microLoanStatus);
        LRViewOrderRequestsJPanel orderStatus=new LRViewOrderRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Order Status",orderStatus);
        //LRViewSubsidyRequestsJPanel subsidyStatus=new LRViewSubsidyRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        //jTabbedPane.add("Subsidy Status",subsidyStatus);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        requestTestJButton1 = new javax.swing.JButton();
        requestTestJButton3 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(245, 170, 122));

        requestTestJButton.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(153, 0, 51));
        requestTestJButton.setText("Request Loan");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 51, 102));
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        requestTestJButton1.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        requestTestJButton1.setForeground(new java.awt.Color(153, 0, 51));
        requestTestJButton1.setText("Order Supplies");
        requestTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton1ActionPerformed(evt);
            }
        });

        requestTestJButton3.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        requestTestJButton3.setForeground(new java.awt.Color(153, 0, 51));
        requestTestJButton3.setText("Request Micro Loan");
        requestTestJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(requestTestJButton)
                            .addGap(128, 128, 128)
                            .addComponent(requestTestJButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(requestTestJButton1)
                            .addGap(264, 264, 264))
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestTestJButton)
                    .addComponent(requestTestJButton3)
                    .addComponent(requestTestJButton1))
                .addContainerGap(368, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("LRRequestBankLoanJPanel", new LRRequestBankLoanJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void requestTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("LROrderSuppliesJPanel", new LROrderSuppliesJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButton1ActionPerformed

    private void requestTestJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("LRRequestMicroLoanJPanel", new LRRequestMicroLoanJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton requestTestJButton1;
    private javax.swing.JButton requestTestJButton3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
